#!/usr/bin/env bash
# encrypt.sh — encrypt your register with age (passphrase mode).
#
# Usage:
#   scripts/encrypt.sh [INPUT] [OUTPUT]
#
#   INPUT   plaintext register        (default: estate.yaml)
#   OUTPUT  encrypted file to write   (default: INPUT.age)
#
# You will be prompted for a passphrase. Press Enter at the prompt to
# have age generate a strong one for you — recommended, since you will
# never need to remember it: it gets split into shares, not memorised.
#
# NOTE: ssss-split accepts at most 128 ASCII characters, so keep the
# passphrase within that (age's autogenerated ones are well within it).
set -euo pipefail

IN="${1:-estate.yaml}"
OUT="${2:-${IN}.age}"

if ! command -v age >/dev/null 2>&1; then
  echo "error: 'age' is not installed." >&2
  echo "  macOS:         brew install age" >&2
  echo "  Debian/Ubuntu: sudo apt install age" >&2
  exit 1
fi

if [ ! -f "$IN" ]; then
  echo "error: input file not found: $IN" >&2
  echo "hint: copy examples/estate.example.yaml to estate.yaml and edit it." >&2
  exit 1
fi

# Validate first so you never seal a broken register. Skips quietly if
# the validator can't run (e.g. PyYAML missing); override with SKIP_VALIDATE=1.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ "${SKIP_VALIDATE:-0}" != "1" ]; then
  if "${PYTHON:-python3}" -c 'import yaml' >/dev/null 2>&1; then
    echo "Validating $IN before encrypting…"
    "$SCRIPT_DIR/validate.sh" "$IN" || {
      echo "error: validation failed — fix the register, or re-run with SKIP_VALIDATE=1." >&2
      exit 1
    }
  else
    echo "note: skipping validation (PyYAML not available — see scripts/validate.sh)." >&2
  fi
fi

if [ -e "$OUT" ]; then
  printf '%s already exists. Overwrite? [y/N] ' "$OUT"
  read -r reply
  case "$reply" in y|Y|yes|YES) ;; *) echo "Aborted."; exit 1 ;; esac
fi

age --encrypt --passphrase -o "$OUT" "$IN"

echo
echo "Encrypted: $OUT"
echo
echo "Next steps:"
echo "  1. Split the passphrase into 2-of-3 shares:  scripts/split-secret.sh"
echo "  2. Test-decrypt before deleting anything:    scripts/decrypt.sh $OUT"
echo "  3. Only then delete the plaintext ($IN) and empty the trash."
echo "     (Keep the .age file in at least two places — it is useless"
echo "     without two shares, so cloud backup is fine.)"
