#!/usr/bin/env bash
# encrypt.sh — encrypt your register with age (passphrase mode).
#
# Prefer scripts/setup.sh — it does encrypt + split + verify in one
# verified chain. This script is the manual building block.
#
# Usage:
#   scripts/encrypt.sh [INPUT] [OUTPUT]
#
#   INPUT   plaintext register        (default: estate.yaml)
#   OUTPUT  encrypted file to write   (default: INPUT.age)
#
# You will be prompted for a passphrase. Press Enter at the prompt to
# have age generate a strong one for you — then save it in your
# password manager, and split it into shares for your executor.
#
# NOTE: ssss-split accepts at most 128 ASCII characters, so keep the
# passphrase within that (age's autogenerated ones are well within it).
set -euo pipefail

IN="${1:-estate.yaml}"
OUT="${2:-${IN}.age}"

if ! command -v age >/dev/null 2>&1; then
  echo "error: 'age' is not installed." >&2
  echo "  macOS:         brew install age" >&2
  echo "  Debian/Ubuntu: sudo apt install age" >&2
  exit 1
fi

if [ ! -f "$IN" ]; then
  echo "error: input file not found: $IN" >&2
  echo "hint: copy examples/estate.example.yaml to estate.yaml and edit it." >&2
  exit 1
fi

# Validate first so you never seal a broken register. The baseline
# validator is pure sh + awk, so this always runs — no dependencies,
# no silent skip.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
echo "Validating $IN before encrypting…"
"$SCRIPT_DIR/validate.sh" "$IN" || {
  echo "error: validation failed — fix the register before sealing it." >&2
  exit 1
}

if [ -e "$OUT" ]; then
  printf '%s already exists. Overwrite? [y/N] ' "$OUT"
  read -r reply
  case "$reply" in y|Y|yes|YES) ;; *) echo "Aborted."; exit 1 ;; esac
fi

age --encrypt --passphrase -o "$OUT" "$IN"

echo
echo "Encrypted: $OUT — this is your Executor File."
echo
echo "Next steps:"
echo "  1. Save the passphrase in your password manager ('Executor File"
echo "     passphrase') — that is your own way back in at review time."
echo "  2. Split the passphrase into 2-of-3 shares:  scripts/split-secret.sh"
echo "  3. Test-decrypt before deleting anything:    scripts/decrypt.sh $OUT"
echo "  4. Store $OUT in at least two private places — it is useless"
echo "     without two shares."
echo "  5. About the plaintext $IN: deleting it reduces exposure but does"
echo "     NOT erase history (SSDs, synced folders, snapshots, editor"
echo "     backups). Work on a full-disk-encrypted machine, keep $IN out"
echo "     of synced folders, and use scripts/review.sh for future edits."
